---
title: "Figure 4:FigR"
output: html_document
date: "2026-04-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(Seurat)
library(Signac)
library(ggplot2)
library(RColorBrewer)
library(dplyr)
library(readxl)
library(ComplexHeatmap)
library(colorRamp2)
library(FNN)
library(chromVAR)
library(doParallel)
library(pheatmap)
library(BuenColors,lib.loc = "~/R/x86_64-pc-linux-gnu-library/4.3/")
library(FigR, lib.loc = "~/R/x86_64-pc-linux-gnu-library/4.3/")
library(BSgenome.Mmusculus.UCSC.mm10)
```


```{r}
TKO_final_arc <- readRDS("/labs/julsage/Debbie/multiome_data/analysis_2/TKO_final_arc.rds")
#dorcs
TKO_final_arc@assays$peaks@ranges<- resize(TKO_final_arc@assays$peaks@ranges, width = 300, fix = "center")
TKO_final_arc@assays$peaks@ranges <- trim(TKO_final_arc@assays$peaks@ranges)

ranges = TKO_final_arc@assays$peaks@ranges
seqlevelsStyle(ranges) <- "UCSC"
peaks = data.frame(ranges)
peaks$peak_ID <- paste0(peaks$seqnames,"-",peaks$start,"-", peaks$end)

peaks_data <- GetAssayData(TKO_final_arc,assay = "peaks",layer = "data")
rownames(peaks_data) = peaks$peak_ID
colData = TKO_final_arc@meta.data

#making ATAC_SE object

ATAC_se <- SummarizedExperiment(
  rowRanges = ranges,
  assays = list(counts = peaks_data),
  colData = colData)

RNA_sm = GetAssayData(TKO_final_arc,assay = "SCT",layer = "data")
RNAmat <- RNA_sm[Matrix::rowSums(RNA_sm)!=0,]

```

```{r}
#Running FigR
cisCorr <- FigR::runGenePeakcorr(ATAC.se = ATAC_se,
                                 RNAmat = RNAmat,
                                 genome = "mm10", # One of hg19, mm10 or hg38 
                                 nCores = 16,
                                 p.cut = NULL, # Set this to NULL and we can filter later
                                 n_bg = 50,
                                 windowPadSize = 100000)
cisCorr.filt <- cisCorr %>% filter(pvalZ <= 0.05)

#Figure 4b
dorcGenes <- dorcJPlot(dorcTab = Ciscorr_filt,
                       cutoff = 5, # No. sig peaks needed to be called a DORC
                       returnGeneList = TRUE, # Set this to FALSE for just the plot
                       force=2)

dorcMat <- getDORCScores(ATAC.se = ATAC_se, # Has to be same SE as used in previous step
                         dorcTab = Ciscorr.filt,
                         geneList = dorcGenes,
                         nCores = 16)

# Smooth dorc scores using cell KNNs (k=30)
dorcMat.s <- smoothScoresNN(NNmat = cellkNN[,1:29],mat = dorcMat,nCores = 16)

# Smooth RNA using cell KNNs
# This takes longer since it's all genes
RNAmat.s <- smoothScoresNN(NNmat = cellkNN[,1:29],mat = RNA_sm,nCores = 16)

#FigR run for TF
figR.d <- runFigRGRN(ATAC.se = ATAC_se, # Must be the same input as used in runGenePeakcorr()
                     dorcTab = cisCorr.filt, # Filtered peak-gene associations
                     genome = "mm10",
                     dorcMat = dorcMat.s,
                     rnaMat = RNAmat.s, 
                     nCores = 16)
```


You can also embed plots, for example:

```{r}
FigR %>% 
  ggplot(aes(Corr.log10P,Enrichment.log10P,color=Score)) + 
  ggrastr::geom_point_rast(size=0.01,shape=16) + 
  theme_classic() + 
  scale_color_gradientn(colours = jdb_palette("solar_extra"),limits=c(-2,2),oob = scales::squish,breaks=scales::breaks_pretty(n=3))

#Fig 4c
rankDrivers(FigR,score.cut = 1.25,rankBy = "nTargets",interactive = FALSE)
rankDrivers(FigR,score.cut = 1.25,rankBy = "meanScore",interactive = TRUE)

plotDrivers(FigR,score.cut =0.50,marker = c("Notch2"))
plotDrivers(FigR,score.cut =0.50,marker = c("Insm1"))
```

```{r}
cutoff_TF = plotfigRHeatmap(figR.d = FigR,
                score.cut = 1.25,
                column_names_gp = gpar(fontsize=5), # from ComplexHeatmap
                show_row_dend = FALSE # from ComplexHeatmap
)

cutoff_TF
```

```{r}
#Subsetting TFs to those expressed in 10 percent of cells
Differential_TF =colnames(cutoff_TF)
data <- data.frame(TKO_final_arc@assays$SCT@data)
fData <- data.frame(gene_short_name = row.names(data), row.names = row.names(data))
fData <- subset(fData, fData$gene_short_name %in% Differential_TF)

PrctCellExpringGene <- function(object, genes, group.by = "all"){
  if(group.by == "all"){
    prct = unlist(lapply(genes,calc_helper, object=object))
    result = data.frame(Markers = genes, Cell_proportion = prct)
    return(result)
  }
  
  else{        
    list = SplitObject(object, group.by)
    factors = names(list)
    
    results = lapply(list, PrctCellExpringGene, genes=genes)
    for(i in 1:length(factors)){
      results[[i]]$Feature = factors[i]
    }
    combined = do.call("rbind", results)
    return(combined)
  }
}

calc_helper <- function(object,genes){
  counts = object[['RNA']]@counts
  ncells = ncol(counts)
  if(genes %in% row.names(counts)){
    sum(counts[genes,]>0)/ncells
  }else{return(NA)}
}

fData$pct=PrctCellExpringGene(TKO_final_arc,genes =fData$gene_short_name)
fData$pct$Cell_proportion = fData$pct$Cell_proportion *100
fData = subset(fData, fData$pct$Cell_proportion >= 10)

data = subset(data, rownames(data) %in% fData$gene_short_name)
data_cor=cor(t(data))

#heatmap
breaksList = seq(-0.45, 0.55, by = 0.01)
pheatmap(data_cor,color = colorRampPalette(rev(brewer.pal(n = 9, name = "RdBu")))(length(breaksList)), # Defines the vector of colors for the legend (it has to be of the same lenght of breaksList)
         breaks = breaksList,border_color = "NA", show_colnames = T, cluster_rows = T, fontsize_row = 6, fontsize_col = 6,)

```

